// SPDX-License-Identifier: PolyForm-Small-Business-1.0.0
//
// 0223 — bulk "AI rename" review dialog. Opens on a selection from the
// Files tab, asks the API for suggestions (router-only), shows
// current → proposed with a checkbox per row (pre-ticked when the
// model's confidence clears the firm threshold), lets staff edit the
// proposed name, and applies the ticked rows.

import { useEffect, useState } from 'react';
import { Button, Modal, Pill, tokens } from '@vibe/ui';

import { api } from '../../api-client';

interface SuggestItem {
  fileId: string;
  current: string | null;
  proposed?: string;
  confidence?: number;
  strategy?: 'pdf_text' | 'pdf_raster' | 'image' | 'metadata';
  summary?: string;
  model?: string | null;
  skippedReason?: string;
}

interface Row extends SuggestItem {
  checked: boolean;
  edited: string;
}

const SKIP_LABELS: Record<string, string> = {
  not_router_mode: 'AI naming is unavailable (not in router mode)',
  file_not_found: 'File not found for this client',
  pending_upload: 'Upload not finished',
  generated_source: 'Generated by Vibe — not renamed',
  already_ai_renamed: 'Already renamed by AI',
  storage_unavailable: 'Could not read the file',
  ai_unavailable: 'AI unavailable',
  ai_failed: 'AI request failed',
  invalid_output: 'AI gave an unusable answer',
};

const STRATEGY_LABELS: Record<NonNullable<SuggestItem['strategy']>, string> = {
  pdf_text: 'text',
  pdf_raster: 'scan',
  image: 'image',
  metadata: 'name only',
};

export function AiRenameDialog({
  clientId,
  fileIds,
  minConfidence,
  onClose,
  onApplied,
}: {
  clientId: string;
  fileIds: string[];
  minConfidence: number;
  onClose: () => void;
  onApplied: (renamed: number) => void;
}): JSX.Element {
  const [rows, setRows] = useState<Row[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<{ renamed: number; skipped: number } | null>(null);

  useEffect(() => {
    let alive = true;
    setRows(null);
    setError(null);
    void api<{ items: SuggestItem[] }>(`/api/staff/clients/${clientId}/files/ai-rename/suggest`, {
      method: 'POST',
      body: JSON.stringify({ fileIds: fileIds.slice(0, 25) }),
    })
      .then((r) => {
        if (!alive) return;
        setRows(
          r.items.map((it) => ({
            ...it,
            checked:
              !!it.proposed && (it.confidence ?? 0) >= minConfidence && it.proposed !== it.current,
            edited: it.proposed ?? '',
          })),
        );
      })
      .catch((e: unknown) => {
        if (!alive) return;
        const status = (e as { status?: number }).status;
        setError(
          status === 404
            ? 'AI naming is not available on this appliance (requires the Vibe AI Router).'
            : e instanceof Error
              ? e.message
              : 'suggest_failed',
        );
      });
    return () => {
      alive = false;
    };
  }, [clientId, fileIds, minConfidence]);

  const ticked = rows?.filter((r) => r.checked && r.edited.trim()) ?? [];

  async function apply(): Promise<void> {
    if (ticked.length === 0) return;
    setBusy(true);
    setError(null);
    try {
      const r = await api<{ renamed: unknown[]; skipped: unknown[] }>(
        `/api/staff/clients/${clientId}/files/ai-rename/apply`,
        {
          method: 'POST',
          body: JSON.stringify({
            items: ticked.map((t) => ({
              fileId: t.fileId,
              newFilename: t.edited.trim(),
              ...(t.confidence !== undefined ? { confidence: t.confidence } : {}),
              ...(t.model ? { model: t.model } : {}),
            })),
          }),
        },
      );
      setResult({ renamed: r.renamed.length, skipped: r.skipped.length });
      onApplied(r.renamed.length);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'apply_failed');
    } finally {
      setBusy(false);
    }
  }

  const cell: React.CSSProperties = {
    padding: '6px 8px',
    fontSize: 12,
    borderBottom: `1px solid ${tokens.color.border}`,
    verticalAlign: 'middle',
  };

  return (
    <Modal title="AI rename" onClose={onClose} minWidth={720} maxWidth={960}>
      {result ? (
        <>
          <p style={{ fontSize: 13 }}>
            Renamed <strong>{result.renamed}</strong> file{result.renamed === 1 ? '' : 's'}
            {result.skipped ? `, ${result.skipped} skipped` : ''}. Originals are kept — use{' '}
            <em>Revert AI rename</em> on a file to undo.
          </p>
          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <Button onClick={onClose}>Done</Button>
          </div>
        </>
      ) : (
        <>
          <p style={{ margin: '0 0 10px', fontSize: 13, color: tokens.color.textMuted }}>
            Names are proposed from each document&apos;s contents using the firm naming pattern.
            Rows at or above {Math.round(minConfidence * 100)}% confidence are pre-ticked; edit any
            name before applying.
          </p>
          {error && (
            <p style={{ color: tokens.color.danger, fontSize: 13, margin: '0 0 10px' }}>{error}</p>
          )}
          {rows === null && !error && (
            <p style={{ fontSize: 13, color: tokens.color.textMuted }}>
              Reading {fileIds.length} file{fileIds.length === 1 ? '' : 's'}…
            </p>
          )}
          {rows && (
            <div style={{ maxHeight: '55vh', overflowY: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr>
                    <th style={{ ...cell, width: 28 }}>
                      <input
                        type="checkbox"
                        aria-label="Select all"
                        checked={rows.length > 0 && rows.every((r) => r.checked || !r.proposed)}
                        onChange={(e) =>
                          setRows(
                            rows.map((r) => ({ ...r, checked: !!r.proposed && e.target.checked })),
                          )
                        }
                      />
                    </th>
                    <th style={{ ...cell, textAlign: 'left' }}>Current</th>
                    <th style={{ ...cell, textAlign: 'left' }}>Proposed</th>
                    <th style={{ ...cell, width: 110 }}>Confidence</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r, i) => (
                    <tr key={r.fileId} style={{ opacity: r.proposed ? 1 : 0.65 }}>
                      <td style={cell}>
                        <input
                          type="checkbox"
                          aria-label={`Rename ${r.current ?? ''}`}
                          disabled={!r.proposed}
                          checked={r.checked}
                          onChange={(e) =>
                            setRows(
                              rows.map((x, j) =>
                                j === i ? { ...x, checked: e.target.checked } : x,
                              ),
                            )
                          }
                        />
                      </td>
                      <td
                        style={{
                          ...cell,
                          fontFamily: tokens.font.mono,
                          color: tokens.color.textMuted,
                        }}
                      >
                        {r.current ?? '—'}
                      </td>
                      <td style={cell}>
                        {r.proposed ? (
                          <>
                            <input
                              value={r.edited}
                              onChange={(e) =>
                                setRows(
                                  rows.map((x, j) =>
                                    j === i ? { ...x, edited: e.target.value } : x,
                                  ),
                                )
                              }
                              style={{
                                width: '100%',
                                fontFamily: tokens.font.mono,
                                fontSize: 12,
                                padding: '4px 6px',
                                border: `1px solid ${tokens.color.border}`,
                                borderRadius: 4,
                                background: tokens.color.surface,
                                color: tokens.color.text,
                              }}
                            />
                            {r.summary && (
                              <div
                                style={{
                                  fontSize: 11,
                                  color: tokens.color.textMuted,
                                  marginTop: 2,
                                }}
                              >
                                {r.summary}
                              </div>
                            )}
                          </>
                        ) : (
                          <span style={{ color: tokens.color.textMuted }}>
                            {SKIP_LABELS[r.skippedReason ?? ''] ?? r.skippedReason}
                          </span>
                        )}
                      </td>
                      <td style={{ ...cell, textAlign: 'center' }}>
                        {r.confidence !== undefined && (
                          <Pill
                            tone={
                              r.confidence >= minConfidence
                                ? 'success'
                                : r.confidence >= 0.4
                                  ? 'warning'
                                  : 'neutral'
                            }
                          >
                            {Math.round(r.confidence * 100)}%
                          </Pill>
                        )}{' '}
                        {r.strategy && (
                          <span style={{ fontSize: 10, color: tokens.color.textMuted }}>
                            {STRATEGY_LABELS[r.strategy]}
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 14 }}>
            <Button variant="secondary" onClick={onClose} disabled={busy}>
              Cancel
            </Button>
            <Button onClick={() => void apply()} disabled={busy || ticked.length === 0}>
              {busy ? 'Renaming…' : `Rename ${ticked.length} file${ticked.length === 1 ? '' : 's'}`}
            </Button>
          </div>
        </>
      )}
    </Modal>
  );
}
