// SPDX-License-Identifier: PolyForm-Internal-Use-1.0.0
//
// Runs Drizzle migrations against DATABASE_URL. Full schema migration set
// generated by drizzle-kit lands in Phase 2; for now this script applies
// the hand-written SQL files in packages/db/migrations in lexical order.

import { readdir, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import postgres from 'postgres';

const here = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(here, '..', '..', 'migrations');

async function main(): Promise<void> {
  const url = process.env['DATABASE_URL'];
  if (!url) {
    throw new Error('DATABASE_URL is required');
  }
  const sql = postgres(url, { max: 1 });
  try {
    await sql`CREATE TABLE IF NOT EXISTS schema_migrations (filename text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`;
    const applied = new Set(
      (await sql<{ filename: string }[]>`SELECT filename FROM schema_migrations`).map(
        (r) => r.filename,
      ),
    );

    const files = (await readdir(migrationsDir))
      .filter((f) => f.endsWith('.sql'))
      .sort((a, b) => a.localeCompare(b));

    for (const f of files) {
      if (applied.has(f)) {
        // eslint-disable-next-line no-console
        console.log(`skip  ${f}`);
        continue;
      }
      const body = await readFile(join(migrationsDir, f), 'utf8');
      // eslint-disable-next-line no-console
      console.log(`apply ${f}`);
      await sql.unsafe(body);
      await sql`INSERT INTO schema_migrations (filename) VALUES (${f})`;
    }
  } finally {
    await sql.end({ timeout: 5 });
  }
}

main().catch((err: unknown) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
