#!/usr/bin/env bash
# =============================================================================
# install-detect-llm.sh — Detect hardware capabilities and select a local LLM
#
# Runs at first boot of the Vibe Practice Management appliance. Inspects RAM, CPU,
# and (if present) GPU, then chooses the right local model and pulls it via
# Ollama. Writes the choice to ./ai.config so the API server picks it up.
#
# Per QUESTIONS.md Q15:
#   - ≥24GB RAM + AVX2  → Mistral Small 24B Q4_K_M
#   - ≥16GB RAM         → Qwen3-8B Q4_K_M (default for GMKtec M6 spec)
#   - ≥8GB RAM          → Phi-3-mini Q4_K_M
#   - <8GB RAM          → disable local AI, suggest cloud fallback
#
# Override post-install in admin → AI settings.
# =============================================================================

set -euo pipefail

OLLAMA_URL="${AI_LOCAL_URL:-http://localhost:11434}"
CONFIG_OUT="${1:-./ai.config}"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
log() {
  echo "[install-detect-llm] $*"
}

abort() {
  log "ERROR: $*"
  exit 1
}

# -----------------------------------------------------------------------------
# Detect total RAM in GB
# -----------------------------------------------------------------------------
detect_ram_gb() {
  if [[ -f /proc/meminfo ]]; then
    awk '/MemTotal:/ {printf "%d", $2 / 1024 / 1024}' /proc/meminfo
  elif command -v sysctl >/dev/null 2>&1; then
    # macOS dev fallback
    sysctl -n hw.memsize | awk '{printf "%d", $1 / 1024 / 1024 / 1024}'
  else
    echo "0"
  fi
}

# -----------------------------------------------------------------------------
# Detect AVX2 support (matters for 24B quantized inference performance)
# -----------------------------------------------------------------------------
detect_avx2() {
  if [[ -f /proc/cpuinfo ]]; then
    if grep -q '\bavx2\b' /proc/cpuinfo; then
      echo "yes"
    else
      echo "no"
    fi
  else
    echo "unknown"
  fi
}

# -----------------------------------------------------------------------------
# Wait for Ollama to become reachable
# -----------------------------------------------------------------------------
wait_for_ollama() {
  local max_wait=60
  local elapsed=0
  while ! curl -fsS "${OLLAMA_URL}/api/tags" >/dev/null 2>&1; do
    if (( elapsed >= max_wait )); then
      abort "Ollama not reachable at ${OLLAMA_URL} after ${max_wait}s"
    fi
    log "Waiting for Ollama at ${OLLAMA_URL}..."
    sleep 2
    ((elapsed += 2))
  done
  log "Ollama is reachable"
}

# -----------------------------------------------------------------------------
# Pull a model via Ollama
# -----------------------------------------------------------------------------
pull_model() {
  local model="$1"
  log "Pulling ${model} via Ollama (this may take several minutes)..."
  if curl -fsS -X POST "${OLLAMA_URL}/api/pull" \
       -H "Content-Type: application/json" \
       -d "{\"name\":\"${model}\"}" >/dev/null; then
    log "Pulled ${model} successfully"
  else
    abort "Failed to pull ${model}"
  fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
  log "Detecting hardware capabilities..."

  local ram_gb
  ram_gb=$(detect_ram_gb)
  log "RAM: ${ram_gb} GB"

  local avx2
  avx2=$(detect_avx2)
  log "AVX2: ${avx2}"

  local model=""
  local model_name=""
  local rationale=""

  if (( ram_gb >= 24 )) && [[ "${avx2}" == "yes" ]]; then
    model="mistral-small:24b-q4_K_M"
    model_name="Mistral Small 24B Q4_K_M"
    rationale="High-end: ≥24GB RAM with AVX2"
  elif (( ram_gb >= 16 )); then
    model="qwen3:8b-q4_K_M"
    model_name="Qwen3-8B Q4_K_M"
    rationale="Mid-tier: ≥16GB RAM (GMKtec M6 spec or better)"
  elif (( ram_gb >= 8 )); then
    model="phi3:mini-q4_K_M"
    model_name="Phi-3-mini Q4_K_M"
    rationale="Low-tier: 8-16GB RAM, limited model selection"
  else
    log "Insufficient RAM for local AI (${ram_gb}GB < 8GB minimum)"
    log "Writing config with AI disabled. Use cloud AI or upgrade hardware."
    cat > "${CONFIG_OUT}" <<EOF
# Generated by install-detect-llm.sh at $(date -Iseconds)
AI_LOCAL_ENABLED=false
AI_LOCAL_MODEL=
AI_LOCAL_RATIONALE=Insufficient RAM (${ram_gb}GB < 8GB minimum)
AI_DETECTED_RAM_GB=${ram_gb}
AI_DETECTED_AVX2=${avx2}
EOF
    log "Done — config written to ${CONFIG_OUT}"
    exit 0
  fi

  log "Selected: ${model_name}"
  log "Rationale: ${rationale}"

  wait_for_ollama
  pull_model "${model}"

  cat > "${CONFIG_OUT}" <<EOF
# Generated by install-detect-llm.sh at $(date -Iseconds)
AI_LOCAL_ENABLED=true
AI_LOCAL_MODEL=${model}
AI_LOCAL_RATIONALE=${rationale}
AI_DETECTED_RAM_GB=${ram_gb}
AI_DETECTED_AVX2=${avx2}
EOF

  log "Done — config written to ${CONFIG_OUT}"
}

main "$@"
